services:
  - type: web
    name: agriorbit-api
    env: node
    rootDir: .
    plan: free
    buildCommand: npm install && npm run prisma:generate
    startCommand: npm run prisma:migrate:deploy && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agriorbit-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: OTP_SECRET
        sync: false
      - key: ACCESS_TOKEN_TTL_SECONDS
        value: "900"
      - key: REFRESH_TOKEN_TTL_SECONDS
        value: "2592000"
      - key: FRONTEND_URL
        value: https://agriorbit.vercel.app
      - key: FRONTEND_ALLOW_CREDENTIALS
        value: "true"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false

databases:
  - name: agriorbit-db
    plan: free
    databaseName: agriorbit
    user: agriorbit
